[package]
name = "rof_rs_core"
description = "Rust Object Format Core API for Rust. Please refer to the main crate to use Rust Object Format in your project."
version = "0.1.1"
edition = "2021"
license="ISC"
repository="https://github.com/Jamzy01/rof"

[dependencies]
