[package]
name = "rust_object_format"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rof_rs_core = { path = "./core" }
rof_rs_macros = { path = "./macros" }